### ISSUE TITLE
UnboundLocalError: local variable 'log_types' referenced before assignment in 1.0b4

### ISSUE THREAD

**Issue by rarelam** [davehunt/pytest-selenium#38]
Hi,

I have upgraded pytest-selenium from 1.0b2 to 1.0b4. The error in command prompt I got is different between both.

1.0b2
![1 0b2](https://cloud.githubusercontent.com/assets/1460421/10603494/df2be3d0-7750-11e5-86b5-b225663c08f9.png)

1.0b4
![1 0b4](https://cloud.githubusercontent.com/assets/1460421/10603501/e5985aaa-7750-11e5-8527-439ff8bfa3a8.png)

Both error generated was because URL is blank while I try to get the page title. I was using local remote Firefox driver when getting this error.

Personally I think the error for 1.0b4 is due to the plugin crashed after web driver throwing exception.

I didn't have chance to try with 1.0b3. Sorry for that.

**Comment by davehunt** [comment]
@rarelam please can you paste full tracebacks instead of screenshots - it's not possible to see from your images the root cause of the first issue. I think I've fixed the problem shown in your second issue but even with my fix you must be hitting something else to get into this state. Can you try installing from my `issue38` branch and reporting back:

```bash
pip install git+git://github.com/davehunt/pytest-selenium.git@issue38
```

**Comment by rarelam** [comment]
before fix:

```
C:\Users\siongwai\Desktop\tutorial>py.test --driver Remote --capability browserN
ame firefox tests\test_google.py
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: C:\Users\siongwai\Desktop\tutorial, inifile:
plugins: html-1.7, selenium-1.0b4, variables-1.2
collected 1 items

tests\test_google.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\main.py", line 90,
in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\main.py", line 121,
 in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrapper
s, kwargs)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\main.py", line 146,
 in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=
nextitem)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrapper
s, kwargs)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)

INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 253, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\runner.py", line 65
, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\runner.py", line 75
, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\runner.py", line 12
1, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)

INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrapper
s, kwargs)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)

INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 249, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\skipping.py", line
170, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "c:\python27\lib\site-packages\_pytest\vendored_packages\p
luggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\python27\lib\site-packages\pytest_selenium\pytest_sele
nium.py", line 133, in pytest_runtest_makereport
INTERNALERROR>     for log_type in log_types:
INTERNALERROR> UnboundLocalError: local variable 'log_types' referenced before a
ssignment

====================== 1 pytest-warnings in 3.69 seconds ======================

```

**Comment by rarelam** [comment]
After fix

```
C:\Users\siongwai\Desktop\tutorial>py.test --driver Remote --capability browserN
ame firefox tests\test_google.py
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: C:\Users\siongwai\Desktop\tutorial, inifile:
plugins: html-1.7, selenium-1.0b4, variables-1.2
collected 1 items

tests\test_google.py F

================================== FAILURES ===================================
___________________________ TestGoogle.test_google ____________________________

self = <tests.test_google.TestGoogle instance at 0x030B6558>
selenium = <selenium.webdriver.remote.webdriver.WebDriver (session="8ce8e63a-ac9
0-4c16-aa73-5dcf71ce55e1")>
base_url = None

    @pytest.mark.nondestructive
    def test_google(self, selenium, base_url):
        driver = Common(selenium)

>       driver.go_to_page(base_url)

tests\test_google.py:12:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pages\common.py:13: in go_to_page
    self.selenium.get(site)
c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py:213: in get

    self.execute(Command.GET, {'url': url})
c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py:201: in exe
cute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x030D0510
>
response = {'class': 'org.openqa.selenium.remote.Response', 'hCode': 1033455, 's
essionId': '8ce8e63a-ac90-4c16-aa73-5dcf71ce55e1', 'state': 'unhandled error', .
..}

    def check_response(self, response):
        """
            Checks that a JSON response from the WebDriver does not have an erro
r.

            :Args:
             - response - The JSON response from the WebDriver server as a dicti
onary
               object.

            :Raises: If the response contains an error message.
            """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return

        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                value = json.loads(value_json)
                status = value['error']
                message = value['message']

        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = WebDriverException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = WebDriverException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        else:
            exception_class = WebDriverException
        value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        message = ''
        if 'message' in value:
            message = value['message']

        screen = None
        if 'screen' in value:
            screen = value['screen']

        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous
>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymo
us>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException and 'alert' in v
alue:
            raise exception_class(message, screen, stacktrace, value['alert'].ge
t('text'))
>       raise exception_class(message, screen, stacktrace)
E       WebDriverException: Message: null value in entry: url=null
E       Screenshot: available via screen
E       Stacktrace:
E           at com.google.common.collect.CollectPreconditions.checkEntryNotNull
(CollectPreconditions.java:33)
E           at com.google.common.collect.SingletonImmutableBiMap.<init> (Singlet
onImmutableBiMap.java:39)
E           at com.google.common.collect.ImmutableBiMap.of (ImmutableBiMap.java:
57)
E           at com.google.common.collect.ImmutableMap.of (ImmutableMap.java:80)
E           at org.openqa.selenium.remote.RemoteWebDriver.get (RemoteWebDriver.j
ava:306)
E           at sun.reflect.GeneratedMethodAccessor89.invoke (None:-1)
E           at sun.reflect.DelegatingMethodAccessorImpl.invoke (None:-1)
E           at java.lang.reflect.Method.invoke (None:-1)
E           at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke
(EventFiringWebDriver.java:102)
E           at com.sun.proxy.$Proxy1.get (None:-1)
E           at org.openqa.selenium.support.events.EventFiringWebDriver.get (Even
tFiringWebDriver.java:160)
E           at org.openqa.selenium.remote.server.handler.ChangeUrl.call (ChangeU
rl.java:40)
E           at org.openqa.selenium.remote.server.handler.ChangeUrl.call (ChangeU
rl.java:1)
E           at java.util.concurrent.FutureTask.run (None:-1)
E           at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSe
ssion.java:176)
E           at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
E           at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
E           at java.lang.Thread.run (None:-1)

c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py:181: Web
DriverException
------------------------------- pytest-selenium -------------------------------
URL: about:blank
================= 1 failed, 1 pytest-warnings in 7.12 seconds =================

```

**Comment by davehunt** [comment]
You base URL is `None`, which is what's causing the second issue. I'll merge my fix for log_types. If your empty base URL turns out to be related to pytest-selenium please raise a new issue.
